/**
 * Canonical catalog for all 44 CMS section presets.
 * Source of truth for categories, audit flags, and library UX.
 */

export type PresetLibraryCategory =
  | "page_headers"
  | "content"
  | "galleries"
  | "conversion_cta"
  | "forms_contact"
  | "social_proof"
  | "process_steps"
  | "comparison"
  | "locations"
  | "staff_dynamic"
  | "memos_notices";

export type PresetLibraryVisibility = "promoted" | "standard" | "hidden" | "merge_into";

export type PresetAuditAction = "keep" | "merge" | "hide" | "rename";

export interface PresetReadiness {
  showcase_preview: boolean;
  page_builder_starter: boolean;
  admin_field_schema: boolean;
  image_size_guidance: boolean;
  responsive_layout: boolean;
  mobile_admin_preview: boolean;
}

export interface SectionPresetCatalogEntry {
  preset_key: string;
  display_name: string;
  library_category: PresetLibraryCategory;
  best_use_case: string;
  supported_fields: string[];
  recommended_image_size: string | null;
  editable_settings: string[];
  layout_variants: string[];
  default_settings: Record<string, string | boolean | number>;
  maps_to_library_type?: string;
  component_path?: string;
  library_visibility: PresetLibraryVisibility;
  audit_action: PresetAuditAction;
  audit_note?: string;
  merge_into_preset_key?: string;
  duplicate_group?: string;
  readiness: PresetReadiness;
}

export const PRESET_LIBRARY_CATEGORIES: {
  id: PresetLibraryCategory;
  label: string;
  description: string;
  sort_order: number;
}[] = [
  {
    id: "page_headers",
    label: "Page Headers",
    description: "Openers for inner pages and homepage hero.",
    sort_order: 1,
  },
  {
    id: "content",
    label: "Content",
    description: "Copy, media splits, FAQs, values, and video blocks.",
    sort_order: 2,
  },
  {
    id: "galleries",
    label: "Galleries",
    description: "Multi-image layouts and collages.",
    sort_order: 3,
  },
  {
    id: "conversion_cta",
    label: "Conversion / CTA",
    description: "Bands that drive a primary action.",
    sort_order: 4,
  },
  {
    id: "forms_contact",
    label: "Forms / Contact",
    description: "Lead forms and contact layouts.",
    sort_order: 5,
  },
  {
    id: "social_proof",
    label: "Social Proof",
    description: "Testimonials and star reviews.",
    sort_order: 6,
  },
  {
    id: "process_steps",
    label: "Process / Steps",
    description: "How-it-works steps and timelines.",
    sort_order: 7,
  },
  {
    id: "comparison",
    label: "Comparison",
    description: "Side-by-side or table comparisons (reserved).",
    sort_order: 8,
  },
  {
    id: "locations",
    label: "Locations",
    description: "Stores, maps, and directions.",
    sort_order: 9,
  },
  {
    id: "staff_dynamic",
    label: "Staff / Dynamic",
    description: "Repeater-driven team rosters.",
    sort_order: 10,
  },
  {
    id: "memos_notices",
    label: "Memos / Notices",
    description: "Short copy in a white notice panel.",
    sort_order: 11,
  },
];

const R_SHOWCASE: PresetReadiness = {
  showcase_preview: true,
  page_builder_starter: false,
  admin_field_schema: false,
  image_size_guidance: true,
  responsive_layout: true,
  mobile_admin_preview: false,
};

const R_STARTER: PresetReadiness = {
  ...R_SHOWCASE,
  page_builder_starter: true,
  admin_field_schema: true,
};

function e(
  partial: Omit<SectionPresetCatalogEntry, "readiness"> & {
    readiness?: Partial<PresetReadiness>;
  },
): SectionPresetCatalogEntry {
  const base = partial.maps_to_library_type
    ? { ...R_SHOWCASE, ...partial.readiness }
    : { ...R_SHOWCASE, ...partial.readiness };
  if (
    partial.maps_to_library_type &&
    ["hero", "text_block", "image_text", "cta_band", "card_grid", "faq", "stats", "form", "locations", "split_feature"].includes(
      partial.maps_to_library_type,
    )
  ) {
    return {
      ...partial,
      readiness: {
        ...R_STARTER,
        mobile_admin_preview: false,
        ...partial.readiness,
      },
    };
  }
  return { ...partial, readiness: base };
}

/** All 44 presets — ordered by category sort_order, then display_name */
export const SECTION_PRESET_CATALOG: SectionPresetCatalogEntry[] = [
  // —— Page Headers (6) ——
  e({
    preset_key: "split_hero",
    display_name: "Homepage split hero",
    library_category: "page_headers",
    best_use_case: "Homepage above-the-fold only — headline, collage, dual CTAs.",
    supported_fields: [
      "eyebrow",
      "headline",
      "subheadline",
      "collage_images[4]",
      "cta_primary_label",
      "cta_primary_url",
      "cta_secondary_label",
      "cta_secondary_url",
    ],
    recommended_image_size: "Collage tiles: 800×600 min per tile (4:3)",
    editable_settings: ["variant", "image_layout", "text_alignment"],
    layout_variants: ["split_collage", "split_single_image"],
    default_settings: { variant: "split_collage", image_layout: "collage_4" },
    maps_to_library_type: "hero",
    component_path: "components/cms/presets/PresetSplitHero.tsx",
    library_visibility: "promoted",
    audit_action: "keep",
    duplicate_group: "hero_collage",
  }),
  e({
    preset_key: "page_header_card",
    display_name: "Header: Card (CMS default)",
    library_category: "page_headers",
    best_use_case: "Default inner-page header — matches live CMS hero card.",
    supported_fields: ["eyebrow", "headline", "subheadline", "cta_label", "cta_url", "image_url"],
    recommended_image_size: "Optional bg: 1920×1080 (16:9)",
    editable_settings: ["variant", "layout_variant", "cta_label", "cta_href"],
    layout_variants: ["light", "dark"],
    default_settings: { variant: "light", layout_variant: "page_card" },
    maps_to_library_type: "hero",
    component_path: "components/cms/presets/headers/PresetPageHeaderCard.tsx",
    library_visibility: "promoted",
    audit_action: "keep",
    duplicate_group: "inner_page_header",
  }),
  e({
    preset_key: "page_header_compact",
    display_name: "Header: Compact title",
    library_category: "page_headers",
    best_use_case: "Utility and policy pages — minimal chrome.",
    supported_fields: ["eyebrow", "headline", "subheadline"],
    recommended_image_size: null,
    editable_settings: ["layout_variant"],
    layout_variants: ["compact"],
    default_settings: { layout_variant: "compact" },
    maps_to_library_type: "text_block",
    component_path: "components/cms/presets/headers/PresetPageHeaderCompact.tsx",
    library_visibility: "standard",
    audit_action: "keep",
  }),
  e({
    preset_key: "page_header_dark_band",
    display_name: "Header: Dark band",
    library_category: "page_headers",
    best_use_case: "Section chapter openers on dark charcoal.",
    supported_fields: ["eyebrow", "headline", "subheadline"],
    recommended_image_size: null,
    editable_settings: ["variant", "full_bleed"],
    layout_variants: ["dark_band"],
    default_settings: { variant: "dark", full_bleed: true },
    maps_to_library_type: "hero",
    component_path: "components/cms/presets/headers/PresetPageHeaderDarkBand.tsx",
    library_visibility: "standard",
    audit_action: "keep",
    audit_note: "Similar to CTA band — use header for titles, CTA band for conversion.",
    duplicate_group: "dark_full_bleed",
  }),
  e({
    preset_key: "page_header_image_banner",
    display_name: "Header: Image banner",
    library_category: "page_headers",
    best_use_case: "Campaign or community pages with photography.",
    supported_fields: ["image_url", "eyebrow", "headline", "subheadline"],
    recommended_image_size: "1920×800 min (wide banner)",
    editable_settings: ["layout_variant", "overlay"],
    layout_variants: ["image_banner"],
    default_settings: { layout_variant: "image_banner", overlay: "gradient" },
    maps_to_library_type: "hero",
    component_path: "components/cms/presets/headers/PresetPageHeaderImageBanner.tsx",
    library_visibility: "standard",
    audit_action: "keep",
    duplicate_group: "image_banner",
  }),
  e({
    preset_key: "page_header_minimal",
    display_name: "Header: Breadcrumb + title",
    library_category: "page_headers",
    best_use_case: "Legal, FAQ index, and shallow content pages.",
    supported_fields: ["breadcrumbs[]", "headline", "meta_line"],
    recommended_image_size: null,
    editable_settings: ["layout_variant"],
    layout_variants: ["minimal"],
    default_settings: { layout_variant: "minimal" },
    maps_to_library_type: "text_block",
    component_path: "components/cms/presets/headers/PresetPageHeaderMinimal.tsx",
    library_visibility: "standard",
    audit_action: "keep",
  }),

  // —— Content (9) ——
  e({
    preset_key: "text_intro",
    display_name: "Centered text intro",
    library_category: "content",
    best_use_case: "Mission statement or pause between visual blocks.",
    supported_fields: ["eyebrow", "headline", "body"],
    recommended_image_size: null,
    editable_settings: ["alignment", "width"],
    layout_variants: ["center", "left"],
    default_settings: { alignment: "center" },
    maps_to_library_type: "text_block",
    component_path: "components/cms/presets/PresetTextIntro.tsx",
    library_visibility: "promoted",
    audit_action: "keep",
    audit_note: "Differs from memos — no white box wrapper.",
    duplicate_group: "plain_copy",
  }),
  e({
    preset_key: "image_text",
    display_name: "Image + text (with CTA)",
    library_category: "content",
    best_use_case: "About, services, or features with photo and action.",
    supported_fields: ["eyebrow", "headline", "body", "image_url", "cta_label", "cta_url"],
    recommended_image_size: "1200×900 (4:3)",
    editable_settings: ["image_position", "mobile_text_first", "media_type", "show_cta"],
    layout_variants: ["image_left", "image_right"],
    default_settings: { image_position: "left", mobile_text_first: true, show_cta: true },
    maps_to_library_type: "image_text",
    component_path: "components/cms/presets/PresetImageText.tsx",
    library_visibility: "promoted",
    audit_action: "keep",
    duplicate_group: "image_text_family",
  }),
  e({
    preset_key: "text_image_editorial",
    display_name: "Image + text (editorial, no CTA)",
    library_category: "content",
    best_use_case: "Heritage or leadership copy without a button.",
    supported_fields: ["eyebrow", "headline", "body", "image_url"],
    recommended_image_size: "1000×1200 (portrait-friendly)",
    editable_settings: ["image_position", "show_cta", "tone"],
    layout_variants: ["text_left", "text_right"],
    default_settings: { show_cta: false, image_position: "right" },
    maps_to_library_type: "image_text",
    component_path: "components/cms/presets/PresetTextImageEditorial.tsx",
    library_visibility: "merge_into",
    merge_into_preset_key: "image_text",
    audit_action: "merge",
    audit_note: "Expose as image_text layout variant: show_cta=false.",
    duplicate_group: "image_text_family",
  }),
  e({
    preset_key: "mixed_media_story",
    display_name: "Mixed media story",
    library_category: "content",
    best_use_case: "Campaign or community storytelling with alternating blocks.",
    supported_fields: ["eyebrow", "headline", "story_blocks[]"],
    recommended_image_size: "Per block: 1200×900",
    editable_settings: ["rhythm", "block_count"],
    layout_variants: ["3_blocks", "5_blocks"],
    default_settings: { rhythm: "alternating" },
    maps_to_library_type: "split_feature",
    component_path: "components/cms/presets/PresetMixedMediaStory.tsx",
    library_visibility: "standard",
    audit_action: "keep",
  }),
  e({
    preset_key: "card_grid_values",
    display_name: "Values card grid",
    library_category: "content",
    best_use_case: "Promises, benefits, or service pillars (icon + title + body).",
    supported_fields: ["eyebrow", "headline", "cards[]"],
    recommended_image_size: "Icons: SVG or 128×128",
    editable_settings: ["columns", "icon_style"],
    layout_variants: ["2_col", "3_col", "4_col"],
    default_settings: { columns: 4 },
    maps_to_library_type: "card_grid",
    component_path: "components/cms/presets/PresetCardGridValues.tsx",
    library_visibility: "promoted",
    audit_action: "keep",
  }),
  e({
    preset_key: "faq_accordion",
    display_name: "FAQ accordion",
    library_category: "content",
    best_use_case: "Policies, buying FAQs, service questions.",
    supported_fields: ["eyebrow", "headline", "faq_items[]"],
    recommended_image_size: null,
    editable_settings: ["allow_multiple_open", "style"],
    layout_variants: ["single_open", "two_column"],
    default_settings: { allow_multiple_open: false },
    maps_to_library_type: "faq",
    component_path: "components/cms/presets/PresetFaqAccordion.tsx",
    library_visibility: "promoted",
    audit_action: "keep",
  }),
  e({
    preset_key: "video_hero",
    display_name: "Video hero",
    library_category: "content",
    best_use_case: "Full-width brand or experience video above the fold.",
    supported_fields: ["video_url", "poster_url", "headline", "body"],
    recommended_image_size: "Poster: 1920×1080; video 16:9 or 21:9",
    editable_settings: ["layout_variant", "aspect"],
    layout_variants: ["video_hero"],
    default_settings: { layout_variant: "video_hero", aspect: "21/9" },
    maps_to_library_type: "custom_html",
    component_path: "components/cms/presets/video/PresetVideoHero.tsx",
    library_visibility: "standard",
    audit_action: "keep",
    duplicate_group: "video_block",
  }),
  e({
    preset_key: "video_text_split",
    display_name: "Video + text split",
    library_category: "content",
    best_use_case: "Virtual tour or explainer beside copy.",
    supported_fields: ["video_url", "headline", "body", "cta_label", "cta_url"],
    recommended_image_size: "Poster: 1200×900",
    editable_settings: ["media_type", "image_position"],
    layout_variants: ["video_left", "video_right"],
    default_settings: { media_type: "video", image_position: "left" },
    maps_to_library_type: "image_text",
    component_path: "components/cms/presets/video/PresetVideoTextSplit.tsx",
    library_visibility: "merge_into",
    merge_into_preset_key: "image_text",
    audit_action: "merge",
    audit_note: "Use image_text with media_type=video.",
    duplicate_group: "image_text_family",
  }),
  e({
    preset_key: "video_gallery",
    display_name: "Video gallery",
    library_category: "content",
    best_use_case: "Multiple clips — tours, testimonials, events.",
    supported_fields: ["videos[] (url, title, duration, poster_url)"],
    recommended_image_size: "Thumbnails: 640×360 (16:9)",
    editable_settings: ["layout_variant", "columns"],
    layout_variants: ["video_gallery"],
    default_settings: { layout_variant: "video_gallery" },
    maps_to_library_type: "card_grid",
    component_path: "components/cms/presets/video/PresetVideoGallery.tsx",
    library_visibility: "standard",
    audit_action: "keep",
    duplicate_group: "video_block",
  }),

  // —— Galleries (5) ——
  e({
    preset_key: "gallery_bento",
    display_name: "Gallery: Bento",
    library_category: "galleries",
    best_use_case: "Editorial community or lifestyle photo mosaic.",
    supported_fields: ["eyebrow", "headline", "gallery_images[8]"],
    recommended_image_size: "Mixed; min 800px wide per tile",
    editable_settings: ["layout_variant"],
    layout_variants: ["bento"],
    default_settings: { layout_variant: "bento" },
    maps_to_library_type: "custom_html",
    component_path: "components/cms/presets/gallery/GalleryGrid.tsx",
    library_visibility: "promoted",
    audit_action: "keep",
    duplicate_group: "gallery_8",
  }),
  e({
    preset_key: "gallery_uniform",
    display_name: "Gallery: Uniform grid",
    library_category: "galleries",
    best_use_case: "Team photos, stores, or events — predictable grid.",
    supported_fields: ["eyebrow", "headline", "gallery_images[8]"],
    recommended_image_size: "800×600 (4:3) per image",
    editable_settings: ["layout_variant", "aspect_ratio"],
    layout_variants: ["uniform"],
    default_settings: { layout_variant: "uniform", aspect_ratio: "4/3" },
    maps_to_library_type: "custom_html",
    component_path: "components/cms/presets/gallery/GalleryGrid.tsx",
    library_visibility: "promoted",
    audit_action: "keep",
    duplicate_group: "gallery_8",
  }),
  e({
    preset_key: "gallery_featured_lead",
    display_name: "Gallery: Featured lead",
    library_category: "galleries",
    best_use_case: "One hero image plus supporting gallery.",
    supported_fields: ["featured_image", "gallery_images[7]"],
    recommended_image_size: "Featured: 1200×900; thumbs: 600×450",
    editable_settings: ["layout_variant"],
    layout_variants: ["featured_lead"],
    default_settings: { layout_variant: "featured_lead" },
    maps_to_library_type: "custom_html",
    component_path: "components/cms/presets/gallery/GalleryGrid.tsx",
    library_visibility: "standard",
    audit_action: "keep",
    duplicate_group: "gallery_8",
  }),
  e({
    preset_key: "gallery_rhythm_rows",
    display_name: "Gallery: Rhythm rows",
    library_category: "galleries",
    best_use_case: "Magazine-style row rhythm (3+2+3).",
    supported_fields: ["gallery_images[8]"],
    recommended_image_size: "800×600 mixed crops",
    editable_settings: ["layout_variant"],
    layout_variants: ["rhythm_rows"],
    default_settings: { layout_variant: "rhythm_rows" },
    maps_to_library_type: "custom_html",
    component_path: "components/cms/presets/gallery/GalleryGrid.tsx",
    library_visibility: "hidden",
    audit_action: "hide",
    audit_note: "Showcase only until validated; overlaps bento/uniform.",
    duplicate_group: "gallery_8",
  }),
  e({
    preset_key: "gallery_dual_collage",
    display_name: "Gallery: Dual collage",
    library_category: "galleries",
    best_use_case: "Rare — doubles homepage collage motif.",
    supported_fields: ["collage_left[4]", "collage_right[4]"],
    recommended_image_size: "Same as homepage collage tiles",
    editable_settings: ["layout_variant"],
    layout_variants: ["dual_collage"],
    default_settings: { layout_variant: "dual_collage" },
    maps_to_library_type: "custom_html",
    component_path: "components/cms/presets/gallery/GalleryGrid.tsx",
    library_visibility: "hidden",
    audit_action: "hide",
    audit_note: "Near-duplicate of split_hero collage — keep in showcase, hide from picker.",
    duplicate_group: "hero_collage",
  }),

  // —— Conversion / CTA (2) ——
  e({
    preset_key: "cta_banner",
    display_name: "CTA banner",
    library_category: "conversion_cta",
    best_use_case: "Late-page conversion — inventory or contact.",
    supported_fields: ["headline", "body", "cta_primary", "cta_secondary", "background_image_url"],
    recommended_image_size: "Optional bg: 1920×600",
    editable_settings: ["overlay", "full_bleed", "text_align"],
    layout_variants: ["gradient", "image_overlay"],
    default_settings: { overlay: "gradient", full_bleed: true },
    maps_to_library_type: "cta_band",
    component_path: "components/cms/presets/PresetCtaBanner.tsx",
    library_visibility: "promoted",
    audit_action: "keep",
    duplicate_group: "dark_full_bleed",
  }),
  e({
    preset_key: "feature_band",
    display_name: "Feature / stats band",
    library_category: "conversion_cta",
    best_use_case: "Trust metrics or three highlights without photos.",
    supported_fields: ["headline", "subheadline", "highlights[]"],
    recommended_image_size: null,
    editable_settings: ["background", "highlight_count", "full_bleed"],
    layout_variants: ["3_cards", "4_stats"],
    default_settings: { background: "charcoal", highlight_count: 3 },
    maps_to_library_type: "stats",
    component_path: "components/cms/presets/PresetFeatureBand.tsx",
    library_visibility: "promoted",
    audit_action: "keep",
    duplicate_group: "dark_full_bleed",
  }),

  // —— Forms / Contact (3) ——
  e({
    preset_key: "contact_split",
    display_name: "Contact: Split + form",
    library_category: "forms_contact",
    best_use_case: "Store details beside inquiry form.",
    supported_fields: ["headline", "contact_lines[]", "form_fields[]"],
    recommended_image_size: null,
    editable_settings: ["layout_variant"],
    layout_variants: ["contact_split"],
    default_settings: { layout_variant: "contact_split" },
    maps_to_library_type: "form",
    component_path: "components/cms/presets/utility/PresetContactSplit.tsx",
    library_visibility: "standard",
    audit_action: "keep",
  }),
  e({
    preset_key: "form_lead",
    display_name: "Form: Lead capture card",
    library_category: "forms_contact",
    best_use_case: "Matches live CMS form — shortlist / lead modal trigger.",
    supported_fields: ["headline", "subheadline", "form_type", "cta_label"],
    recommended_image_size: null,
    editable_settings: ["layout_variant", "form_type", "lead_action"],
    layout_variants: ["form_lead"],
    default_settings: { layout_variant: "form_lead", form_type: "general-shortlist" },
    maps_to_library_type: "form",
    component_path: "components/cms/presets/utility/PresetFormLead.tsx",
    library_visibility: "promoted",
    audit_action: "keep",
  }),
  e({
    preset_key: "form_compact",
    display_name: "Form: Compact inquiry",
    library_category: "forms_contact",
    best_use_case: "Sidebar-style or footer-adjacent short form.",
    supported_fields: ["headline", "topic_tags[]", "form_fields[]"],
    recommended_image_size: null,
    editable_settings: ["layout_variant"],
    layout_variants: ["form_compact"],
    default_settings: { layout_variant: "form_compact" },
    maps_to_library_type: "form",
    component_path: "components/cms/presets/utility/PresetFormCompact.tsx",
    library_visibility: "standard",
    audit_action: "keep",
  }),

  // —— Social Proof (4) ——
  e({
    preset_key: "testimonial_grid",
    display_name: "Testimonials: Grid",
    library_category: "social_proof",
    best_use_case: "Multiple guest quotes in equal cards.",
    supported_fields: ["eyebrow", "headline", "testimonials[]"],
    recommended_image_size: "Optional avatars: 96×96",
    editable_settings: ["layout_variant"],
    layout_variants: ["testimonial_grid"],
    default_settings: { layout_variant: "testimonial_grid" },
    maps_to_library_type: "card_grid",
    component_path: "components/cms/presets/testimonials/PresetTestimonialGrid.tsx",
    library_visibility: "promoted",
    audit_action: "keep",
    duplicate_group: "testimonials",
  }),
  e({
    preset_key: "testimonial_featured",
    display_name: "Testimonials: Featured quote",
    library_category: "social_proof",
    best_use_case: "One lead quote plus supporting testimonials.",
    supported_fields: ["featured_testimonial_id", "testimonials[]"],
    recommended_image_size: "Optional avatars: 96×96",
    editable_settings: ["layout_variant"],
    layout_variants: ["testimonial_featured"],
    default_settings: { layout_variant: "testimonial_featured" },
    maps_to_library_type: "card_grid",
    component_path: "components/cms/presets/testimonials/PresetTestimonialFeatured.tsx",
    library_visibility: "standard",
    audit_action: "keep",
    duplicate_group: "testimonials",
  }),
  e({
    preset_key: "reviews_summary",
    display_name: "Reviews: Summary band",
    library_category: "social_proof",
    best_use_case: "Aggregate star rating with highlight snippets.",
    supported_fields: ["review_average", "review_count", "reviews[]"],
    recommended_image_size: null,
    editable_settings: ["layout_variant"],
    layout_variants: ["reviews_summary"],
    default_settings: { layout_variant: "reviews_summary" },
    maps_to_library_type: "stats",
    component_path: "components/cms/presets/reviews/PresetReviewsSummary.tsx",
    library_visibility: "promoted",
    audit_action: "keep",
  }),
  e({
    preset_key: "reviews_grid",
    display_name: "Reviews: Card grid",
    library_category: "social_proof",
    best_use_case: "Individual star-rated reviews with source.",
    supported_fields: ["reviews[]"],
    recommended_image_size: null,
    editable_settings: ["layout_variant", "columns"],
    layout_variants: ["reviews_grid"],
    default_settings: { layout_variant: "reviews_grid" },
    maps_to_library_type: "card_grid",
    component_path: "components/cms/presets/reviews/PresetReviewsGrid.tsx",
    library_visibility: "standard",
    audit_action: "keep",
  }),

  // —— Process / Steps (4) ——
  e({
    preset_key: "process_horizontal",
    display_name: "Process: Horizontal steps",
    library_category: "process_steps",
    best_use_case: "4-step sales or service journey on desktop.",
    supported_fields: ["process_steps[] (step, title, body, icon_url)"],
    recommended_image_size: "Icons: 64×64 optional",
    editable_settings: ["layout_variant"],
    layout_variants: ["process_horizontal"],
    default_settings: { layout_variant: "process_horizontal" },
    maps_to_library_type: "card_grid",
    component_path: "components/cms/presets/process/PresetProcessHorizontal.tsx",
    library_visibility: "promoted",
    audit_action: "keep",
    audit_note: "Consider single picker entry 'Process steps' with layout toggle.",
    duplicate_group: "process_layout",
  }),
  e({
    preset_key: "process_vertical",
    display_name: "Process: Vertical steps",
    library_category: "process_steps",
    best_use_case: "Mobile-friendly numbered flow.",
    supported_fields: ["process_steps[]"],
    recommended_image_size: "Icons: 64×64 optional",
    editable_settings: ["layout_variant"],
    layout_variants: ["process_vertical"],
    default_settings: { layout_variant: "process_vertical" },
    maps_to_library_type: "card_grid",
    component_path: "components/cms/presets/process/PresetProcessVertical.tsx",
    library_visibility: "standard",
    audit_action: "keep",
    duplicate_group: "process_layout",
  }),
  e({
    preset_key: "timeline_vertical",
    display_name: "Timeline: Vertical",
    library_category: "process_steps",
    best_use_case: "Company history or campaign chronology.",
    supported_fields: ["timeline_events[] (date, title, body)"],
    recommended_image_size: "Optional event images: 800×600",
    editable_settings: ["layout_variant"],
    layout_variants: ["timeline_vertical"],
    default_settings: { layout_variant: "timeline_vertical" },
    maps_to_library_type: "custom_html",
    component_path: "components/cms/presets/timeline/PresetTimelineVertical.tsx",
    library_visibility: "promoted",
    audit_action: "keep",
    duplicate_group: "timeline_layout",
  }),
  e({
    preset_key: "timeline_horizontal",
    display_name: "Timeline: Horizontal",
    library_category: "process_steps",
    best_use_case: "At-a-glance milestones; scrolls on mobile.",
    supported_fields: ["timeline_events[]"],
    recommended_image_size: "Optional event images: 800×600",
    editable_settings: ["layout_variant"],
    layout_variants: ["timeline_horizontal"],
    default_settings: { layout_variant: "timeline_horizontal" },
    maps_to_library_type: "custom_html",
    component_path: "components/cms/presets/timeline/PresetTimelineHorizontal.tsx",
    library_visibility: "standard",
    audit_action: "keep",
    duplicate_group: "timeline_layout",
  }),

  // —— Locations (4) ——
  e({
    preset_key: "location_grid",
    display_name: "Locations: Store cards",
    library_category: "locations",
    best_use_case: "Multi-store grid with hours and directions CTA.",
    supported_fields: ["locations[]"],
    recommended_image_size: "Optional store photo: 800×600",
    editable_settings: ["layout_variant"],
    layout_variants: ["location_grid"],
    default_settings: { layout_variant: "location_grid" },
    maps_to_library_type: "locations",
    component_path: "components/cms/presets/location/PresetLocationGrid.tsx",
    library_visibility: "promoted",
    audit_action: "keep",
  }),
  e({
    preset_key: "location_split_map",
    display_name: "Locations: Split map",
    library_category: "locations",
    best_use_case: "Single flagship store — details + map embed.",
    supported_fields: ["featured_location_id", "map_embed_url"],
    recommended_image_size: "Map N/A; store photo 1200×900",
    editable_settings: ["layout_variant"],
    layout_variants: ["location_split_map"],
    default_settings: { layout_variant: "location_split_map" },
    maps_to_library_type: "locations",
    component_path: "components/cms/presets/location/PresetLocationSplitMap.tsx",
    library_visibility: "promoted",
    audit_action: "keep",
    duplicate_group: "location_map",
  }),
  e({
    preset_key: "map_multi_location",
    display_name: "Map: Multi-store picker",
    library_category: "locations",
    best_use_case: "Region with many stores — map + location list.",
    supported_fields: ["locations[]", "map_provider", "map_api_key"],
    recommended_image_size: null,
    editable_settings: ["layout_variant"],
    layout_variants: ["map_multi_location"],
    default_settings: { layout_variant: "map_multi_location" },
    maps_to_library_type: "locations",
    component_path: "components/cms/presets/maps/PresetMapMultiLocation.tsx",
    library_visibility: "standard",
    audit_action: "keep",
    duplicate_group: "location_map",
  }),
  e({
    preset_key: "directions_panel",
    display_name: "Directions panel",
    library_category: "locations",
    best_use_case: "One address with Google/Apple/Waze links + parking note.",
    supported_fields: ["address", "parking_notes", "directions_links[]"],
    recommended_image_size: "Map embed responsive height",
    editable_settings: ["layout_variant"],
    layout_variants: ["directions_panel"],
    default_settings: { layout_variant: "directions_panel" },
    maps_to_library_type: "locations",
    component_path: "components/cms/presets/maps/PresetDirectionsPanel.tsx",
    library_visibility: "standard",
    audit_action: "keep",
  }),

  // —— Staff / Dynamic (5) ——
  e({
    preset_key: "staff_grid",
    display_name: "Staff: Card grid",
    library_category: "staff_dynamic",
    best_use_case: "Default team roster — photos and roles.",
    supported_fields: ["staff_members[]"],
    recommended_image_size: "Headshots: 600×600 (1:1)",
    editable_settings: ["layout_variant", "columns"],
    layout_variants: ["staff_grid", "2_col", "4_col"],
    default_settings: { layout_variant: "staff_grid", columns: 3 },
    maps_to_library_type: "card_grid",
    component_path: "components/cms/presets/staff/PresetStaffGrid.tsx",
    library_visibility: "promoted",
    audit_action: "keep",
    duplicate_group: "staff_roster",
  }),
  e({
    preset_key: "staff_by_department",
    display_name: "Staff: By department",
    library_category: "staff_dynamic",
    best_use_case: "Auto-grouped org chart by department field.",
    supported_fields: ["staff_members[]", "group_by"],
    recommended_image_size: "Headshots: 600×600 (1:1)",
    editable_settings: ["group_by", "layout_variant"],
    layout_variants: ["staff_by_department"],
    default_settings: { group_by: "department" },
    maps_to_library_type: "card_grid",
    component_path: "components/cms/presets/staff/PresetStaffByDepartment.tsx",
    library_visibility: "standard",
    audit_action: "keep",
    duplicate_group: "staff_roster",
  }),
  e({
    preset_key: "staff_spotlight",
    display_name: "Staff: Spotlight + grid",
    library_category: "staff_dynamic",
    best_use_case: "Leadership profile plus team grid.",
    supported_fields: ["featured_staff_id", "staff_members[]"],
    recommended_image_size: "Featured: 800×800; grid: 600×600",
    editable_settings: ["layout_variant"],
    layout_variants: ["staff_spotlight"],
    default_settings: { layout_variant: "staff_spotlight" },
    maps_to_library_type: "card_grid",
    component_path: "components/cms/presets/staff/PresetStaffSpotlight.tsx",
    library_visibility: "standard",
    audit_action: "keep",
    duplicate_group: "staff_roster",
  }),
  e({
    preset_key: "staff_list_compact",
    display_name: "Staff: Compact list",
    library_category: "staff_dynamic",
    best_use_case: "Long rosters — directory style.",
    supported_fields: ["staff_members[]"],
    recommended_image_size: "Avatars: 96×96",
    editable_settings: ["layout_variant"],
    layout_variants: ["staff_list_compact"],
    default_settings: { layout_variant: "staff_list_compact" },
    maps_to_library_type: "card_grid",
    component_path: "components/cms/presets/staff/PresetStaffListCompact.tsx",
    library_visibility: "hidden",
    audit_action: "hide",
    audit_note: "Niche — promote grid or compact via settings later.",
    duplicate_group: "staff_roster",
  }),
  e({
    preset_key: "staff_location_tabs",
    display_name: "Staff: Location filter",
    library_category: "staff_dynamic",
    best_use_case: "Filter team by store location.",
    supported_fields: ["staff_members[]", "filter_field", "store_locations[]"],
    recommended_image_size: "Headshots: 600×600",
    editable_settings: ["filter_field", "layout_variant"],
    layout_variants: ["staff_location_tabs"],
    default_settings: { filter_field: "location" },
    maps_to_library_type: "card_grid",
    component_path: "components/cms/presets/staff/PresetStaffLocationTabs.tsx",
    library_visibility: "standard",
    audit_action: "keep",
    audit_note: "Overlaps map multi-location — staff vs store map use cases differ.",
  }),

  // —— Memos / Notices (2) ——
  e({
    preset_key: "memo_simple",
    display_name: "Memo: Simple notice",
    library_category: "memos_notices",
    best_use_case: "Holiday hours, disclaimers, short alerts in white box.",
    supported_fields: ["body"],
    recommended_image_size: null,
    editable_settings: ["layout_variant", "width"],
    layout_variants: ["memo_simple"],
    default_settings: { layout_variant: "memo", width: "narrow" },
    maps_to_library_type: "text_block",
    component_path: "components/cms/presets/utility/PresetMemoSimple.tsx",
    library_visibility: "promoted",
    audit_action: "keep",
    duplicate_group: "memo_box",
  }),
  e({
    preset_key: "memo_titled",
    display_name: "Memo: Titled notice",
    library_category: "memos_notices",
    best_use_case: "Scheduling notes or policy callouts with headline.",
    supported_fields: ["headline", "body"],
    recommended_image_size: null,
    editable_settings: ["layout_variant"],
    layout_variants: ["memo_titled"],
    default_settings: { layout_variant: "memo_titled" },
    maps_to_library_type: "text_block",
    component_path: "components/cms/presets/utility/PresetMemoTitled.tsx",
    library_visibility: "standard",
    audit_action: "keep",
    duplicate_group: "memo_box",
  }),
];

export function getPresetsByCategory(
  category: PresetLibraryCategory,
): SectionPresetCatalogEntry[] {
  return SECTION_PRESET_CATALOG.filter((p) => p.library_category === category);
}

export function getPickerVisiblePresets(): SectionPresetCatalogEntry[] {
  return SECTION_PRESET_CATALOG.filter(
    (p) => p.library_visibility === "promoted" || p.library_visibility === "standard",
  );
}

export function getCatalogCategoryCounts(): Record<PresetLibraryCategory, number> {
  const counts = {} as Record<PresetLibraryCategory, number>;
  for (const cat of PRESET_LIBRARY_CATEGORIES) {
    counts[cat.id] = SECTION_PRESET_CATALOG.filter(
      (p) => p.library_category === cat.id,
    ).length;
  }
  return counts;
}

export const PRESET_CLEANUP_SUMMARY = {
  keep: SECTION_PRESET_CATALOG.filter((p) => p.audit_action === "keep").length,
  merge: SECTION_PRESET_CATALOG.filter((p) => p.audit_action === "merge").length,
  hide: SECTION_PRESET_CATALOG.filter((p) => p.audit_action === "hide").length,
  rename: SECTION_PRESET_CATALOG.filter((p) => p.audit_action === "rename").length,
  picker_visible: getPickerVisiblePresets().length,
  showcase_total: SECTION_PRESET_CATALOG.length,
} as const;
